#!/bin/sh

# starts the virtual cable server
# YUGE 
# wittich
# 2/1/2018
# moved to this location 4/5/2018



DAEMON=/usr/bin/xvcServer
NAME=xvcServer-init
DESC="Xilinx Virtual Cable server"
PIDFILE=/var/run/xvcServer.pid

set -e


test ! -r /etc/default/xvcServer || . /etc/default/xvcServer

test -x "$DAEMON" || exit 0



case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -o -b -p $PIDFILE -m -x "$DAEMON" 
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
        # copied from above
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
        sleep 1
	start-stop-daemon -S -o -b -p $PIDFILE -m -x "$DAEMON" 
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
